#!/usr/bin/env python3
"""Extract the Chinook data section into the rig's per-engine load files.

Source of truth: ``tests/fixtures/source/Chinook_PostgreSql.sql`` (Chinook
1.4.5, the file the fixture bundles were generated from). This tool copies its
"Populate Tables" section — the INSERT statements, nothing else — verbatim
into:

    rig/chinook/postgres/02-chinook-data.sql
    rig/chinook/sqlserver/02-chinook-data.sql

Verbatim works on both engines because of three properties of the source:

* String literals are ``N'...'`` with ``''`` escaping — the SQL Server form.
  PostgreSQL accepts ``N''`` too, but NOT verbatim here: an ``N''`` literal is
  typed ``bpchar`` there, and bpchar-to-varchar assignment treats trailing
  spaces as padding and silently drops them — which erased ``'Edinburgh '``,
  the one padded value in Chinook and the very value the trim-normalization
  record exists to catch. The PostgreSQL output therefore strips the ``N``
  prefix (plain literals are untyped and load byte-exact); the SQL Server
  output keeps it, because there dropping it would mangle unicode instead.
  Backslashes appear only inside literals, where both engines (PostgreSQL
  under its default ``standard_conforming_strings``) treat them literally.
* Every multi-row INSERT holds at most 1000 rows — SQL Server's limit.
* Temporal literals are ``'YYYY/M/D'`` strings. Each engine header pins the
  field order (``SET datestyle`` / ``SET DATEFORMAT``) so neither engine's
  locale defaults get a vote.

The outputs are checked in; rerun this tool only when the source file
changes, and commit source and outputs together.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "tests" / "fixtures" / "source" / "Chinook_PostgreSql.sql"
MARKER = "INSERT INTO genre"

PG_HEADER = """\
-- Chinook data for the crawler acceptance rig — PostgreSQL.
-- Generated by rig/chinook/tools/extract-data.py from
-- tests/fixtures/source/Chinook_PostgreSql.sql (Chinook 1.4.5). Do not edit;
-- rerun the tool. The datestyle pin makes '1962/2/18' parse as
-- year/month/day regardless of the server's locale defaults.

SET datestyle = ISO, YMD;

"""

MSSQL_HEADER = """\
-- Chinook data for the crawler acceptance rig — SQL Server.
-- Generated by rig/chinook/tools/extract-data.py from
-- tests/fixtures/source/Chinook_PostgreSql.sql (Chinook 1.4.5). Do not edit;
-- rerun the tool. The DATEFORMAT pin makes '1962/2/18' parse as
-- year/month/day regardless of the login's language defaults.

USE chinook;
GO
SET DATEFORMAT ymd;
SET NOCOUNT ON;

"""


def main() -> None:
    text = SOURCE.read_text(encoding="utf-8")
    data = text[text.index(MARKER) :]
    # The section runs to the end of the file and holds only INSERTs — the
    # assertion keeps that true when the source is ever swapped out.
    for line in data.splitlines():
        stripped = line.strip()
        assert (
            not stripped
            or stripped.startswith(("INSERT INTO", "("))
        ), f"non-INSERT line in the data section: {stripped[:80]!r}"
    data = data.rstrip("\n") + "\n"

    # Strip the N prefix for PostgreSQL — see the module docstring. The
    # pattern consumes each whole literal ('' escapes included), so a value
    # like "Guns N'' Roses" is never split mid-string, and the quote-count
    # check pins that no literal boundary moved.
    pg_data = re.sub(r"N'((?:[^']|'')*)'", r"'\1'", data)
    assert pg_data.count("'") == data.count("'")

    targets = {
        ROOT / "rig" / "chinook" / "postgres" / "02-chinook-data.sql": (
            PG_HEADER, pg_data),
        ROOT / "rig" / "chinook" / "sqlserver" / "02-chinook-data.sql": (
            MSSQL_HEADER, data),
    }
    for path, (header, body) in targets.items():
        path.write_text(header + body, encoding="utf-8")
        rows = body.count("\n    (")
        print(f"wrote {path.relative_to(ROOT)} ({rows} rows)")


if __name__ == "__main__":
    main()
